#!/usr/bin/env python3
"""Regenerate the pymavlink dialect this project's Cube link needs.

    python3 comms/gen_dialect.py            build it
    python3 comms/gen_dialect.py --verify   only check what is already installed

WHY THIS IS NEEDED AT ALL. DETECTION_TARGET_DATA (42050) and GCS_TARGET_BEARING
(42051) are this airframe's own messages. Stock pymavlink has never heard of
either, and the two failure modes are asymmetric and both nasty:

  * sending    -- mav.detection_target_data_send() raises AttributeError, loudly,
                  but only when that code path first fires. In flight, that is the
                  first detection.
  * receiving  -- an incoming 42051 is an unknown message id and is dropped
                  SILENTLY. It looks exactly like firmware that does not send it.

A SEPARATE DIALECT, NOT A PATCHED ardupilotmega.py. The generated module is
called `thermal_link` and sits beside ardupilotmega.py rather than overwriting
it. Two reasons: a `pip install --upgrade pymavlink` overwrites ardupilotmega.py
and would silently revert the link to a build that cannot send, and there is
another consumer of pymavlink on this host whose own dialect must not be
disturbed.

THE XML IN comms/mavlink/ IS THE SOURCE OF TRUTH. This script splices those
message definitions into a dialect that `<include>`s stock ardupilotmega.xml, so
the generated module is ardupilotmega plus our two messages and nothing else.
"""
import argparse
import os
import pathlib
import sys
import xml.etree.ElementTree as ET

DIALECT = "thermal_link"
MSG_DIR = pathlib.Path(__file__).resolve().parent / "mavlink"
WANT = {"DETECTION_TARGET_DATA": 42050, "GCS_TARGET_BEARING": 42051}

HEADER = """<?xml version="1.0"?>
<!-- GENERATED by comms/gen_dialect.py from comms/mavlink/*.msg.xml. Do not edit.
     ardupilotmega, plus this airframe's two custom messages. Kept as a SEPARATE
     dialect so a pymavlink upgrade cannot revert the link to a build that can
     neither send 42050 nor decode 42051, and so the other pymavlink consumer on
     this host keeps its own dialect untouched.
     Selected at runtime by comms/dialect.py via MAVLINK_DIALECT={dialect}. -->
"""


def dialect_dir():
    """Where pymavlink resolves MAVLINK_DIALECT from: its own dialects/v20 package."""
    import pymavlink
    d = pathlib.Path(pymavlink.__path__[0]) / "dialects" / "v20"
    if not (d / "ardupilotmega.xml").is_file():
        sys.exit(f"{d}/ardupilotmega.xml is missing -- cannot <include> the base "
                 f"dialect. Is this a complete pymavlink install?")
    return d


def collect_messages():
    """The <message> elements from comms/mavlink/, as serialised XML."""
    out, found = [], {}
    for path in sorted(MSG_DIR.glob("*.msg.xml")):
        root = ET.parse(path).getroot()          # rejects a malformed file here, not in mavgen
        for msg in root.findall("messages/message"):
            name, mid = msg.get("name"), int(msg.get("id"))
            if name in found:
                sys.exit(f"{path.name}: {name} is defined twice ({found[name]} and {path.name})")
            found[name] = path.name
            out.append(ET.tostring(msg, encoding="unicode").strip())
    for name, mid in WANT.items():
        if name not in found:
            sys.exit(f"no definition for {name} ({mid}) in {MSG_DIR} -- the link needs it")
    return out, found


def expected_messages():
    """{NAME: (id, crc_extra, [fieldnames])} as comms/mavlink/*.msg.xml defines it.

    Parsed with pymavlink's OWN mavparse, so crc_extra and the field order are
    computed by the same code mavgen would use rather than reimplemented here:
    the answer is what a correct build of this XML WOULD contain, not an
    approximation of it.
    """
    import os
    os.environ.setdefault("MAVLINK20", "1")     # before the generator is imported
    from pymavlink.generator import mavparse
    out = {}
    for path in sorted(MSG_DIR.glob("*.msg.xml")):
        for m in mavparse.MAVXML(str(path), "2.0").message:
            out[m.name] = (m.id, m.crc_extra, [f.name for f in m.fields])
    return out


def compare(lookup):
    """(ok, detail) -- does what `lookup` provides match the XML in every field?

    `lookup` maps a message name to its generated class, or to None. Checking
    the FIELD LIST and not just the id is the whole point: an id-only check
    passes a dialect generated before a field was added, and the send then goes
    out through pymavlink's trailing force_mavlink1 parameter instead of the
    field -- which is how capture_latency_us silently failed on 2026-09-16.
    crc_extra is checked too, because it is what the Cube drops messages over.
    """
    try:
        want = expected_messages()
    except Exception as e:                       # pragma: no cover - broken install
        return False, f"could not parse {MSG_DIR}: {e}"
    problems = []
    for name, mid in sorted(WANT.items(), key=lambda kv: kv[1]):
        if name not in want:
            problems.append(f"{name} ({mid}) has no definition in {MSG_DIR}")
            continue
        want_id, want_crc, want_fields = want[name]
        cls = lookup(name)
        if cls is None:
            problems.append(f"{name} ({mid}) absent")
            continue
        if cls.id != want_id:
            problems.append(f"{name} has id {cls.id}, expected {want_id}")
        if cls.crc_extra != want_crc:
            problems.append(f"{name} has crc_extra {cls.crc_extra}, expected {want_crc}"
                            " -- the Cube will drop every one of these")
        have_fields = list(cls.fieldnames)
        if have_fields != want_fields:
            lost = [f for f in want_fields if f not in have_fields]
            extra = [f for f in have_fields if f not in want_fields]
            bits = []
            if lost:
                bits.append("missing " + ", ".join(lost))
            if extra:
                bits.append("unexpected " + ", ".join(extra))
            if not bits:
                bits.append(f"field order differs: {have_fields} vs {want_fields}")
            problems.append(f"{name} is STALE -- " + "; ".join(bits))
    if problems:
        return False, "; ".join(problems)
    detail = ", ".join(f"{n}={want[n][0]}({len(want[n][2])} fields)"
                       for n, _ in sorted(WANT.items(), key=lambda kv: kv[1]))
    return True, detail


def verify():
    """Import the installed dialect and check it against the XML, field by field.

    Imports the generated module directly rather than going through mavutil, so
    the answer is about the dialect itself and not about anything the environment
    happens to have set.
    """
    try:
        mod = __import__(f"pymavlink.dialects.v20.{DIALECT}", fromlist=[DIALECT])
    except ImportError as e:
        return False, f"dialect {DIALECT} is not installed ({e})"
    return compare(lambda name: getattr(mod, f"MAVLink_{name.lower()}_message", None))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--verify", action="store_true",
                    help="do not build; just report on what is installed")
    args = ap.parse_args()

    if args.verify:
        ok, detail = verify()
        print(("ok   " if ok else "FAIL ") + detail)
        return 0 if ok else 1

    msgs, found = collect_messages()
    for name, src in sorted(found.items()):
        print(f"  message  {name:<24} from {src}")

    dst = dialect_dir()
    xml_path = dst / f"{DIALECT}.xml"
    py_path = dst / f"{DIALECT}.py"

    body = HEADER.format(dialect=DIALECT) + "<mavlink>\n  <include>ardupilotmega.xml</include>\n  <messages>\n"
    body += "\n".join("    " + m.replace("\n", "\n    ") for m in msgs)
    body += "\n  </messages>\n</mavlink>\n"
    xml_path.write_text(body)
    print(f"  wrote    {xml_path}")

    # MAVLINK20 has to be set before pymavlink's generator is imported, for the same
    # reason it does at runtime: the v1.0 module cannot represent an id above 255.
    os.environ.setdefault("MAVLINK20", "1")
    from pymavlink.generator import mavgen
    opts = mavgen.Opts(output=str(py_path), wire_protocol="2.0",
                       language="Python3", validate=False)
    if not mavgen.mavgen(opts, [str(xml_path)]):
        sys.exit("mavgen failed -- see its output above")
    print(f"  wrote    {py_path}  ({py_path.stat().st_size // 1024} KB)")

    ok, detail = verify()
    print(("  ok       " if ok else "  FAIL     ") + detail)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
